/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CoverPlay: typeof import('./src/components/coverPlay.vue')['default']
    ElAffix: typeof import('element-plus/es')['ElAffix']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElResult: typeof import('element-plus/es')['ElResult']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Footer: typeof import('./src/components/layout/comps/footer/index.vue')['default']
    Header: typeof import('./src/components/layout/comps/header/index.vue')['default']
    IconPark: typeof import('./src/components/iconPark.vue')['default']
    Layout: typeof import('./src/components/layout/index.vue')['default']
    Login: typeof import('./src/components/layout/comps/login/index.vue')['default']
    Menu: typeof import('./src/components/layout/comps/menu/index.vue')['default']
    More: typeof import('./src/components/layout/comps/header/comps/more.vue')['default']
    PlayerAction: typeof import('./src/components/layout/comps/footer/comps/playerAction.vue')['default']
    PlayerController: typeof import('./src/components/layout/comps/footer/comps/playerController.vue')['default']
    PlayerSlider: typeof import('./src/components/layout/comps/footer/comps/playerSlider.vue')['default']
    PlayerSong: typeof import('./src/components/layout/comps/footer/comps/playerSong.vue')['default']
    PlayerVolumeSlider: typeof import('./src/components/layout/comps/footer/comps/playerVolumeSlider.vue')['default']
    PlayList: typeof import('./src/components/layout/comps/playList/index.vue')['default']
    PlayListSongItem: typeof import('./src/components/layout/comps/playList/comps/playListSongItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchPop: typeof import('./src/components/layout/comps/header/comps/searchPop.vue')['default']
    SearchSuggest: typeof import('./src/components/layout/comps/header/comps/SearchSuggest.vue')['default']
    Title: typeof import('./src/components/title.vue')['default']
    UserInfo: typeof import('./src/components/layout/comps/header/comps/userInfo.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
